version: '3'
services:
  pma:
    container_name: pma_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - PMA_VOLUME:/data
volumes:
  PMA_VOLUME:

